/**
 * Session Model — MongoDB Schema for Interview Session State
 *
 * This model persists the complete lifecycle of an interview session:
 *   1. Creation: Session is created by POST /start with randomly selected questions
 *   2. Active:   The candidate works on questions, code and transcript stream in
 *   3. Completed: Final report (feedback) is attached by the agent or report generator
 *
 * Schema Design:
 *   - `questions[]`         — All questions selected for this session (up to 2)
 *   - `currentQuestionIndex`— Pointer to which question the candidate is on
 *   - `question`            — The currently active question (denormalized for fast reads)
 *   - `submissions[]`       — Per-question code + transcript snapshots
 *   - `code`                — Live code state (updated as candidate types)
 *   - `transcript[]`        — Conversation transcript between candidate and AI
 *   - `feedback`            — Final evaluation report generated after completion
 *
 * Note: The `question` field duplicates data from `questions[currentQuestionIndex]`.
 * This denormalization is intentional — it allows the frontend to fetch the active
 * question with a single field read instead of array indexing, and it simplifies
 * the Mongoose projection in route handlers.
 */

import mongoose, { Schema, Document } from 'mongoose';

/**
 * ISubmission — Records a single question's code and transcript at submission time.
 *
 * Each time the candidate advances past a question (via /submit-question),
 * a new ISubmission is pushed to session.submissions. This creates a per-question
 * audit trail that the report generator can use to evaluate progression.
 */
interface ISubmission {
  questionIndex: number;
  code: string;
  transcript: Array<{
    role: 'ai' | 'user';
    content: string;
    timestamp: Date;
  }>;
  submittedAt: Date;
}

/**
 * ISession — Full TypeScript interface for a Session document.
 *
 * Key design decisions:
 *   - `sessionId` is a string (not ObjectId) to allow the fixed "intervu-ai-interview"
 *     convention used in the MVP. Can be swapped to UUID for multi-session support.
 *   - `feedback` is optional because it only exists after the interview completes.
 *   - `questions[]` stores the full QuestionDef objects (minus id/difficulty/tags)
 *     so the agent and frontend have all context without querying the question bank.
 */
export interface ISession extends Document {
  sessionId: string;
  status: 'active' | 'completed';

  // Multi-question support
  // All questions selected for this session (populated at POST /start time)
  questions: Array<{
    title: string;
    description: string;
    examples: string[];
    starterCode: string;
    language: string;
    fileName: string;
    visualization?: string;
  }>;
  // Index into questions[] — tracks which question is currently active
  currentQuestionIndex: number;
  // Per-question submission history — appended on each /submit-question call
  submissions: ISubmission[];

  // Current working state (denormalized snapshot of questions[currentQuestionIndex])
  question: {
    title: string;
    description: string;
    examples: string[];
    starterCode: string;
    language: string;
    fileName: string;
    visualization?: string;
  };
  // Live code state — updated continuously as the candidate types
  code: string;
  language: string;
  fileName: string;

  // Conversation transcript — messages between the candidate and the AI agent.
  // Each entry has a role ('ai' or 'user'), content, and timestamp.
  // The transcript is used by the report generator for communication evaluation.
  transcript: Array<{
    role: 'ai' | 'user';
    content: string;
    timestamp: Date;
  }>;

  // Final evaluation report — populated after session completion.
  // Generated by either the Python agent (POST /save-analysis) or the
  // Node report generator (reportGenerator.ts via POST /submit).
  feedback?: {
    correctness: boolean;
    overall_score: number;
    dimension_scores?: {
      problem_solving: number;
      algorithmic_thinking: number;
      code_implementation: number;
      testing: number;
      time_management: number;
      communication: number;
    };
    feedback_markdown: string;
    score?: number; // Legacy field for backwards compatibility
  };
  createdAt: Date;
}

/**
 * SessionSchema — Mongoose schema definition.
 *
 * Key schema choices:
 *   - `sessionId` is unique + required — acts as the primary lookup key
 *   - `questions` is an embedded array (not references) because questions are
 *     selected at session creation and don't change afterward
 *   - `submissions` is also embedded for the same reason — it's append-only
 *   - `transcript` entries use an enum for role to prevent typos
 *   - All date fields default to Date.now for automatic timestamping
 */
const SessionSchema: Schema = new Schema({
  sessionId: { type: String, required: true, unique: true },
  status: { type: String, enum: ['active', 'completed'], default: 'active' },

  // Multi-question support — embedded array of full question definitions
  questions: [{
    title: { type: String, required: true },
    description: { type: String, required: true },
    examples: { type: [String], default: [] },
    starterCode: { type: String, default: '' },
    language: { type: String, default: 'java' },
    fileName: { type: String, default: 'Solution.java' },
    visualization: { type: String },
  }],
  currentQuestionIndex: { type: Number, default: 0 },

  // Per-question submission audit trail
  submissions: [{
    questionIndex: { type: Number, required: true },
    code: { type: String, default: '' },
    transcript: [{
      role: { type: String, enum: ['ai', 'user'], required: true },
      content: { type: String, required: true },
      timestamp: { type: Date, default: Date.now },
    }],
    submittedAt: { type: Date, default: Date.now },
  }],

  // Currently active question — denormalized for O(1) access
  question: {
    title: { type: String, required: true },
    description: { type: String, required: true },
    examples: { type: [String], default: [] },
    starterCode: { type: String, default: '' },
    language: { type: String, default: 'java' },
    fileName: { type: String, default: 'Solution.java' },
    visualization: { type: String },
  },
  code: { type: String, default: '' },
  language: { type: String, default: 'java' },
  fileName: { type: String, default: 'Solution.java' },

  // Conversation transcript between candidate and AI
  transcript: [{
    role: { type: String, enum: ['ai', 'user'], required: true },
    content: { type: String, required: true },
    timestamp: { type: Date, default: Date.now },
  }],

  // Final evaluation report (only set after session completion)
  feedback: {
    correctness: { type: Boolean },
    overall_score: { type: Number },
    dimension_scores: {
      problem_solving: { type: Number },
      algorithmic_thinking: { type: Number },
      code_implementation: { type: Number },
      testing: { type: Number },
      time_management: { type: Number },
      communication: { type: Number }
    },
    feedback_markdown: { type: String },
    score: { type: Number }, // Legacy field
  },
  createdAt: { type: Date, default: Date.now },
});

export default mongoose.model<ISession>('Session', SessionSchema);
